/*
  Warnings:

  - The values [OPTIMIZE_FSRS_PARAMS,REBUILD_FSRS_CACHE] on the enum `JobType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "JobType_new" AS ENUM ('INITIALIZE_CARD_STATES', 'INITIALIZE_LISTENING_CARD_STATES', 'GENERATE_PRACTICE_PDF', 'OPTIMIZE_LISTENING_FSRS_PARAMS', 'REBUILD_LISTENING_FSRS_CACHE', 'BULK_IMPORT_VOCABULARY', 'BULK_IMPORT_STUDENTS', 'BULK_IMPORT_SCHEDULES', 'BULK_IMPORT_FILL_IN_THE_BLANK', 'BULK_IMPORT_GENERIC_DECK', 'OPTIMIZE_VOCABULARY_FSRS_PARAMS', 'OPTIMIZE_GENERIC_FSRS_PARAMS', 'REBUILD_VOCABULARY_FSRS_CACHE', 'REBUILD_GENERIC_FSRS_CACHE');
ALTER TABLE "Job" ALTER COLUMN "type" TYPE "JobType_new" USING ("type"::text::"JobType_new");
ALTER TYPE "JobType" RENAME TO "JobType_old";
ALTER TYPE "JobType_new" RENAME TO "JobType";
DROP TYPE "JobType_old";
COMMIT;
