name: Deploy to Alibaba ECS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into ECS and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USER }}
          key: ${{ secrets.ECS_SSH_KEY }}
          script: |
            set -e
            cd /srv/yingyu || { mkdir -p /srv/yingyu && cd /srv/yingyu; }
            if [ ! -d .git ]; then
              git clone https://github.com/dev-mirzabicer/yingyu.git .
            fi
            if [ ! -f .env.production ]; then
              echo "Missing /srv/yingyu/.env.production on server"; exit 1
            fi
            ./scripts/deploy.sh

